### ISSUE TITLE
Use arena allocator for backup

### ISSUE THREAD

**Issue by FSMaxB** [1984not-GmbH/molch#101]
Currently the protobuf-backups are allocated using `zeroed_malloc`. There's two problems with that:
1. If you forget to free something it's not only a memory leak, but also leaks keys.
2. If the memory were to be swapped out, keys would be written to disk, which is bad.

Possible solution:
------------------------
Make an arena allocator based on `sodium_malloc`. The arena would be a linked list of 4K blocks (or a multiple of that, or less as to leave space for libsodiums internal data structures) allocated with libsodium. Allocations are made consecutively in these 4K chunks. There would just be a pointer that gets increased after every allocation.

If a block is full, another one would be added to the linked list.

Free does nothing. Only when the entire backup is done, all blocks are  freed.

Benefits:
* Higher cache locality
* Memory doesn't get swapped to disk
* Faster allocations (probably, depends on how long mmapping new pages actually takes).
* Backup is protected by guard pages.

The opaque data pointer passed to the allocator function that protobuf-c accepts would point to a class something like this (not sure if the following would even compile):

```cpp
class SodiumArena {
private:
    static const size_t block_size; //size of a block
    std::vector<std::unique_ptr<unsigned char[],SodiumDeleter<unsigned char>> blocks;
    unsigned char* current_pointer; //where are we in the current block?

public:
    SodiumArena();
    /*
     * Returns the next aligned pointer in the current block after current_pointer,
     * if enough space is available. Otherwise creates a new block and returns it's
     * starting address.
     * In both cases then advances the current_pointer by size (after the aligned address).
     */
    void* allocate(size_t size);
};
```

**Comment by wuli133144** [comment]
very good

**Comment by FSMaxB** [comment]
This has been fully implemented on the `cpp` branch.
